# Generated by Django 4.0.3 on 2022-03-22 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0002_profile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='User',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='User',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='profile',
        ),
        migrations.AddField(
            model_name='business',
            name='Owner_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.business'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='Business_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
