# Generated by Django 4.0.3 on 2022-03-22 07:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_remove_posts_post_posts_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='post',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
